---
title: ''
output: bookdown::pdf_document2
date: "`r Sys.Date()`"
---
# Abstract {-}
Warming water temperature as a result of climate change poses a major threat to coldwater organisms. However, the rate of warming is not spatially uniform due to surface-ground-water interactions and stream and watershed characteristics. Coldwater habitats that are most resistant to warming serve as thermal refugia and identifying their locations is critical to regional aquatic conservation planning. We quantified the thermal sensitivity of 203 streams providing current and potential habitat for brook trout (*Salvelinus fontinalis*) across nearly 1,000 linear km of their native range in the southern and central Appalachian Mountains region, USA, and characterized their spatial variability with landscape variables available in the National Hydrography Dataset. Using the Bayesian framework, we calculated the maximum slope of the logistic function relating paired weekly mean air temperature and stream temperature as an index of stream thermal sensitivity. Streams differed greatly in thermal sensitivity and those with more resistant water temperature regimes (i.e., thermal refugia) were consistently characterized by southerly latitudes and groundwater input. Landscape variables derived from a principal component analysis explained 16% of variation in thermal sensitivity, indicating that the existing landscape variables were modestly successful in explaining spatial thermal heterogeneity. Using our model and spatial interpolation, we predicted thermal sensitivity at 8,695 stream segments potentially suitable for brook trout in the study region. Thermal refugia were more common southward presumably due to higher elevations, but elsewhere they were also clustered at finer spatial scales. Our analysis informs prioritizing habitat conservation and restoration of this native salmonid and other aquatic organisms that depend on coldwater habitats in a warming world.  

Keywords: climate refugia, brook trout, stream temperature, landscape, aquatic organisms, southeast USA, thermal sensitivity, Bayesian