---
title: ''
output: bookdown::pdf_document2
date: "`r Sys.Date()`"
---
Our work represents one of the most geographically extensive analyses of thermal habitat for an aquatic species of conservation concern. The paired stream-air temperature data showed much thermal variation among 203 sites distributed along approximately 1,000 km, including some sites where stream temperatures were stable over time (weekly average < 15 $^\circ$C) and others where stream temperatures warmed readily with increasing air temperatures. Spatial thermal variability has been observed in other brook trout studies conducted over more geographically confined areas [@kanno2014; @trumbo2014]. Given the thermal heterogeneity over space and upper thermal limits of brook trout [22-24 $^\circ$C: @eaton1995; @hartman2008; @wehrly2007], our study demonstrates that some current brook trout streams will likely maintain their populations over a long period of time and serve as climate refugia. Notably, principal components derived from landscape variables in the NHD explained __ % of variation in thermal sensitivity among sites, showing that readily available regional landscape data may be sufficient for describing why thermal heterogeneity exits in a region. Overall, our study highlights the importance of embracing spatial thermal variability for identifying thermal refugia and using this knowledge in maximizing the chance of sustaining coldwater species in a large landscape.

We found a latitudinal pattern of thermal refugia locations, where thermally resistant sites were clustered in the southern area (i.e., North Carolina and Tennessee) of the study region. More thermally resistant sites were characterized with cooler maximum average weekly temperatures, and this correlation between different thermal metrics provided further support for the robustness of our thermal refugia predictions. We reason that the latitudinal pattern of thermal sensitivity was due to spatial gradients of elevation in this study area, where elevation peaks in the southern area and decreases northward. Elevation has frequently been linked to thermal regimes that differ over space [@isaak2017; @maheu2016; more REF]. Our finding of more thermally resistant sites in the southern area corroborates with REF, who suggested that brook trout populations would more likely persist in that area than farther north due to projected thermal conditions, and contrasts with @flebbe2006, who did not account for spatially heterogenous stream-air temperature relationships and projected a nearly complete eradication of brook trout populations there in warming scenarios. Smaller clusters of climate refugia were also identified in the northern area such as eastern West Virginia and eastern Maryland. In general, thermal sensitivity of stream temperatures was spatially autocorrelated resulting in clusters of climate refugia, although this is not always the case in our data set and previous studies [@kanno2014; @snyder2015]. Nevertheless, our work is useful for identifying general clusters where thermal refugia mostly likely occur, to guide where conservation and restoration might be prioritized. 

In addition to the conspicuous latitudinal pattern of climate refugia locations, the principal components of landscape variables revealed complexities of thermal controls over space. *In general, water temperature was more buffered against changes in air temperature when streams were located in XXXX.* The degree of groundwater influence, represented by baseflow index, has consistently been identified as a determinant of thermal sensitivity [@beaufort2020; @briggs2018; @johnson2017; @kelleher2012; @tague2007]. In our study, metrics of water velocity (second and fourth axes of PCA) explained spatial variation in thermal sensitivity better than groundwater. We surmise that water velocity may be surrogate for latent determinants of thermal sensitivity such as channel slope and morphology, which regulate solar radiation and surface-groundwater exchange [@caissie2006; @hauer2016]. Similarly, sediment, geology, and landcover may be linked to processes that affect stream temperature resiliency such as the water table depth and water retention in soils [@monk2013; @ryan1991; @snyder2015]. As correlational evidence, the principal components of landscape variables cannot robustly identify ecological processes that generate spatial heterogeneity in stream temperature. Irrespective of the process uncertainties, these statistical relationships were needed in predicting thermal sensitivity for all stream segments potentially occupied by brook trout in the study area. Previous research often used a limited number of landscape covariates to characterize spatial thermal variability [@beaufort2020; @kelleher2012; @tague2007], and multivariate approaches should be considered more frequently especially for predictive purposes. 

The spatial grain of our thermal sensitivity predictions was for NHD stream segments, given the landscape data availability for the large geographic extent of this study. However, thermal heterogeneity can occur within stream segments [@fullerton2017; @kalbus2006; @selker2006] and aquatic organisms may cue in highly localized areas of cold stream temperature to avoid unsuitably high temperatures in summer [@matthews1997; @sullivan2021]. Additional research is warranted to investigate availability of spatially confined thermal refugia in stream segments that were predicted to respond sensitively to air temperatures, and this requires methods to characterize fine-scale thermal heterogeneity [e.g., fiber-optics cable; @selker2006] and habitat use by aquatic organisms [e.g., temperature tags; @hahlbeck2022]. In the meantime, stream segments identified as thermal refugia in our study should be validated and this could be accomplished by deploying additional pairs of stream and air temperature loggers.

In conclusion, this study demonstrates that spatial thermal variability can be characterized by readily available landscape variables for a large region. This knowledge is critical for managing coldwater species in a warming climate and identifying locations of climate refugia [@jones2014]. Importantly, climate refugia should be defined and located based on stream thermal regimes and other key factors. Resistance and resiliency of aquatic populations under climate change depend not only on stream thermal regimes but also vulnerability of habitat to extreme wet (i.e., floods) and dry events (i.e., droughts) and habitat patch size and connectivity which affects post-disturbance recolonization and recovery of the populations [@ebersole2020]. Such an integrative approach to identifying climate refugia is similarly important to strategizing landscape-level conservation of brook trout and other coldwater-dependent organisms in the southern and central Appalachian Mountains region. 




## Landscape Influence

Landscape and hydrologic factors explained the vast majority of variance in stream thermal stability. This thermal stability, as measured by the maximum slope of logistic regression, was most highly influenced by principal component #2, incorporating summer water velocities, followed by principal components __ and __, incorporating __ and __. Water velocity is related to slope, which is generally correlated with thermal stability because low slopes and velocities are more easily heated through radiation and advection. When considered in analyses of thermal sensitivity, stream velocity or slope often take a back seat to groundwater influence [@beaufort2020]. However our results suggest that stream velocity may be more important in explaining stream temperature than previously thought. 

We predicted that groundwater influence, as represented by baseflow index, would be the most important predictor of thermal stability (see @mayer2012 sec. 4.2 for more details). This factor has been commonly identified elsewhere as an influence on thermal stability [@beaufort2020; @briggs2018a; @johnson2020; @kelleher2012; @tague2007]. In the end, the PC including baseflow index has the second strongest effect on thermal stability. This may be due to the fact that groundwater remains difficult to measure and predict over broad spatial scales such as that of our study (Kalbus et al., 2006). Also significantly influential was the principal component incorporating local sediment and landcover. Geology can be directly related to groundwater [@tague2007]. Sedimentation has long been known to influence stream temperatures [@ryan1991], but as a landscape characteristic, sediments have not been linked to stream thermal stability. Mixed forest within the stream catchment has been identified as an important factor in creating coldwater refugia [@monk2013].

While our results support the findings of other authors - namely that groundwater can have important influence on stream thermal stability - they also lend support to hydrologic influences such as streamflow and identify novel linkages such as soil moisture. Future research should seek to identify mechanisms behind these novel influences on stream temperature.

While base flow index was highly ranked in PC __, this PC was eclipsed by those including streamflow and landcover

## Model Comparison

We found that nonlinear and linear regression performed similarly. Research is divided in its assessment of the relative fits of these two models, and differences in fit are often related to the latitude and region of the study area. Researchers at higher latitudes and cooler climates in North America generally favor the fit of logistic regression [@kelleher2012; @mayer2012], while work in warmer climates such as southern Europe [@beaufort2020] generally favors linear regression. Nonlinear fits such as generalized additive models (GAMs) have occasionally been favored as well [@laanaya2017]. Relative fits likely vary by region because differences are mainly attributable to model behavior at high and low air temperatures where nonlinear behavior occurs. In locations where freezing air temperatures are rare (or removed for analysis), linear regressions often fit best. Where air temperatures below freezing are more common, nonlinear fits may be favored. Despite the fact that our study area was at relatively low latitudes, due to its elevation, it can experience freezing temperatures in winter. Future work should seek to establish how linear and nonlinear regressions of thermal stability compare in regions that lack freezing air temperatures.

Despite the fact that nonlinear models can sometimes better explain thermal stability, linear fits remain useful because they allow simple comparisons of slopes between studies. Our estimates of slopes for weekly linear regressions are roughly in line with those reported in previous reports [see Table 3 in @beaufort2020]. Linear slopes were generally lower/higher than findings from other studies, indicating that water temperatures at trout habitat in the southeast US are more/less buffered than those in other regions. 

<!-- Our results continue to establish consensus for improved model fit using temperature measurements aggregated at increasing temporal scales. We found that temperature values summarized at weekly intervals outperformed those summarized at daily intervals. This finding is in agreement with those of other researchers that have compared model fits at multiple temporal scales [@stefan1993; @kelleher2012; @morrill2005]. The supposed reason for this is that by aggregating across a broader temporal interval, the time lag between air and water temperatures can be negated [@stefan1993]. The temperature metrics employed vary by study. @beaufort2020, @kelleher2012, use average temperatures, while @chang2013 use maximum temperatures. We elected to model stream thermal sensitivity using maximum air and water temperatures at daily and weekly intervals. It should be noted that because variance is generally dampened as values are averaged at increasing intervals, modeling average temperature at increasing intervals would by necessity result in improved fit with each increase. By using maximum temperatures, we avoid this bias and employ a measurement that is more biologically relevant to thermally sensitive taxa such as brook trout.  -->
<!-- Nonetheless,  @mohseni1999a, @caissie2001, and @mohseni2003 have all found that the logistic model did not fit well to temperatures grouped at daily intervals.  -->

## Prediction
Effective management of aquatic resources depends heavily on predictive forecasting, and there is a need for informed predictions made at the broad scales at which ecological processes occur [@briggs2018a]. By using widely available landscape characteristics, our methods allow us to predict thermal stability at unsampled brook trout habitat throughout the southeastern USA. Given that our nonlinear model allows the inclusion of site-specific minimum and maximum water temperatures to more accurately fit the air-water temperature relationship, we chose to employ this model for predictions. Predicted stream thermal stability was highly influenced by these inputs of minimum and maximum stream temperatures, as illustrated by the similarity between predicted thermal stability (Fig. \@ref(fig:beta-predictions-plot)) and predicted minimum and maximum stream temperature (Appendix \@ref(fig:min-max-interpolated-map-plot)). Our predictions identified a moderate latitudinal gradient in thermal stability, with more consistently stable water temperatures occurring in the southern half of the study region. This finding is in contradiction to the prevailing thought that northerly brook trout habitat is generally preferable in this study region, and that poor southerly habitat may mark these populations for imminent extirpation [@flebbe2006].  Managers should consider that even if southerly habitat may have higher average water temperatures than northerly habitat, it may still hold value due to its thermal stability. In addition to this latitudinal gradient, we identified several areas marked by stable stream temperatures. These predicted thermal stabilities will be crucial for allocating funding and conservation resources throughout the study region. Predictions such as these can also be used to identify important thermal habitat for small-scale follow up research. Broad scale modeling of aquatic thermal habitat can be particularly useful when combined with microhabitat studies such as ___. Our work adds to a small but growing body of broad-scale thermal predictions in North America [e.g., @maheu2016a; @isaak2017a].

Our gap analysis revealed that a majority of thermally stable brook trout habitat in the study area already lies within protected areas. These protected areas are often highly conserved [@PADUS2022], and at the least are protected from the conversion of natural land cover to anthropogenic land cover. Conversely, this means that nearly half of this habitat remains vulnerable to human impacts and land use conversion. Brook trout are an aquatic indicator species, and they often cohabitate with other sensitive and threatened taxa [@vandusen2005; @vile2018]. Managers and conservationists seeking to conserve land in this region should incorporate stream thermal stability into their considerations.

A common drawback of studies of thermal stablity is that air temperatures are derived from model outputs or the most convenient meteorological station [@beaufort2020; @hare2021; @kelleher2012]. This means that trends in air temperatures used for analysis may not reflect the true trends influencing stream temperature at the local scale [@kanno2014]. Solar radiation and the influence of local topography have been shown to substantial influence variation in the microclimate across the landscape, particularly in mountainous areas [@aalto2017; @tscholl2022]. Furthermore, weather stations are commonly situated in open, flat areas where they miss the thermal effects of topography and tree cover [@defrenne2016; @graae2012]. We overcome this problem by using air temperatures measured in-situ at the same locations where water temperatures are measured. By using these paired air and water temperature loggers, our study design therefore allows the consideration of highly local atmospheric influence on stream temperature.

The use of PCA to reduce the number of landscape variables can limit our ability to assess the influence of any one variable on thermal stability. However, the PCA groups similar variables, meaning that distinguishing between variables contained in the same PC is not so necessary. Essentially, this is a trade-off between considering many variables to identify novel linkages and considering fewer variables to identify specific ecological relationships. 

## Final paragraph - reiterate most important finding
Thermal stability is a critical stream habitat characteristic that is influenced by local hydrologic and landscape factors. As climate change brings warmer and more variable air temperatures to temperate climates, stable and cool habitats will become important climate refugia [@jones2014]. Spatially explicit predictions such as ours offer important insight into regional patterns that may not be visible from localized studies, and these can help with important conservation and management decisions. Our results support and build on previous findings relating local landscape to stream temperatures.