---
title: ''
output: bookdown::pdf_document2
date: "`r Sys.Date()`"
---

Water temperature is a key component of lotic ecosystems, determining species composition, organismal metabolism, and ecosystem functions and productivity [@caissie2006; @poff2002]. Stream temperatures have risen in the last few decades [@kaushal2010] and will continue to rise as global climate change accelerates [@portner2022; @vanvliet2013]. Warming water temperature poses a major threat to the persistence of coldwater organisms, but warming rates are not spatially homogeneous due to surface-groundwater interactions and watershed and localized landscape characteristics [@lisi2013; @winfree2017]. Identifying characteristics of stream habitats that offer refuge from climate warming and predicting their locations is critical to coldwater conservation planning [@ebersole2020].

However, challenges lie in locating climate refugia for coldwater organisms over a broad geographic extent. Stream temperature is influenced by a multitude of atmospheric, hydraulic, and landscape characteristics and processes [@caissie2006; @lisi2015; @poole2001; @webb2008]. Physical temperature models incorporate solar radiation, air-water heat transfer, evapotranspiration, and groundwater input [@caissie2006; @kelleher2012; @lalot2015; @sinokrot1993]. These processes may differ spatially due to local hydrology, riparian shading, and local landcover [@chang2013; @dugdale2018; @garner2015; @mayer2012]. These process-based modeling approaches are difficult to replicate at many sites, especially for predicting temperatures at unsampled sites and consequently strategizing landscape and regional conservation efforts. 

Alternatively, statistical approaches based on the relationships between stream and air temperatures have proliferated to characterize thermal variation among streams [e.g., @crisp1982; @mackey1991; @mohseni1999; @stefan1993; @zhu2018]. Stream-air temperature relationships have been represented by linear [@beaufort2020; @erickson2000] or nonlinear (i.e., logistic) regression [@mohseni1998; @mohseni1999]. The nonlinear approach is best suited to regions characterized with low (<0 $^\circ$C) and high (>25 $^\circ$C) air temperatures. Specifically, stream temperature typically remains above 0 $^\circ$C when surface ice forms in winter, and at elevated air temperature in summer, evaporative cooling mitigates warming rates [@mohseni1998; @mohseni1999]. Stream-air temperature relationships have been modeled from hourly to annual time scales [@caissie2001; @sinokrot1993; @stefan1993; @webb1997], with the time lag between stream and air temperature diminishing over longer temporal scales [@kelleher2012]. Sensitivity of stream temperature relative to changes in air temperature can be used as an indicator of groundwater input, where more temporally stable stream temperature amid air temperature fluctuations signifies this buffered thermal input [@beaufort2020; @hare2023; @kelleher2012]. Thermal sensitivity and average water temperature are often strongly negatively correlated [@luce2014; @devine2021], meaning that cold streams are typically thermally stable. As a result, thermal stability can provide an important signal in identifying thermal refuge for coldwater organisms.

Despite our increasing knowledge of spatial variability in thermal sensitivity, few studies have been undertaken to explain or predict spatial variability using readily available watershed and hydrological data at the national and regional scale [@mayer2012; @trumbo2014] (e.g., US Environmental Protection Agency StreamCat or National Hydrography Dataset (NHD) in the USA). These broad-scale data sets inherently provide coarse-scale habitat characterization. For example, the NHD contains hydrologic data at the stream segment scale, defined as the length of streams between two confluences or from the headwater to the first confluence downstream. Thus, spatial heterogeneity within stream segments and highly localized processes (i.e., groundwater seepage) could be missed, limiting our ability to locate thermal refugia. Despite potential limitations, spatial variability in thermal sensitivity has been attributed to coarse-scale metrics such as riparian conditions, stream size, and geology [@beaufort2020; @chang2013; @mayer2012; @tague2007; @toffolon2015]. As broad-scale stream data become increasingly available, it is important to test their ability to explain and predict thermal sensitivity over a broad geographic extent to inform management of coldwater species of conservation concern.

The brook trout (*Salvelinus fontinalis*) is a coldwater salmonid whose native distribution covers much of eastern North America. Brook trout populations have declined greatly, particularly in their southern native range, due to anthropogenic factors such as habitat loss and fragmentation, non-native species, and introgression with hatchery fish [@hudy2008; @kazyak2022]. As a coldwater species, they cannot withstand prolonged periods of water temperatures exceeding 22-24 $^\circ$C [@eaton1995; @hartman2008; @wehrly2007]. Riverscapes characterized by cool stream temperatures allow brook trout to persist through heat waves and droughts [@hitt2017; @petty2012; @trego2019]. Thus, the ability to identify and predict thermally suitable brook trout habitat over a long period (i.e., thermal refugia) is of great importance for prioritizing streams for conservation and restoration action such as habitat improvement, physical barrier removal, non-native trout removal, and brook trout translocations [@kanno2016a; @white2023]. Stream temperatures have been modeled for brook trout streams in their native range, including the use of paired stream-air temperature measurements [@kanno2014; @letcher2016; @trumbo2014]. However, these studies were limited in their geographical extent and we are not aware of previous work that combined paired stream-air temperature measurements with readily available watershed and hydrological data to describe and predict thermal sensitivity of streams at the regional scale.

We characterized landscape influences on stream thermal sensitivity across nearly 1,000 km of  the native range of brook trout in the southern and central Appalachian Mountains region, USA, using a multi-year data set of paired stream and air temperature measurements. Located at their southernmost native range, the study area has experienced the greatest declines of brook trout populations [@hudy2008]. Our study objectives were two-fold. First, we used widely available landscape and hydrologic metrics to identify determinants of stream thermal sensitivity with a Bayesian hierarchical model of nonlinear relationships between weekly average stream and air temperatures. Second, we used this model to predict thermal sensitivity at unsampled brook trout habitats throughout the study area. In addressing these objectives, we aimed to quantify how much thermal sensitivity varied among streams in the study area and its correlation with landscape characteristics and identify locations of thermal refugia for brook trout in a warming world.